[package]
name = "doc"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.12.1"
miette.workspace = true
mime = "0.3.17"
reqwest.workspace = true
scraper = "0.27.0"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio.workspace = true
