//! Functions service error names returned through [`crate::error::ApiError`].

pub const ERROR_NAMES: &[&str] = &[
    "AsyncConsistentSnapshotError",
    "AsyncFunctionNotSupportedWithTransaction",
    "AsyncInvalidQueryOutputValue",
    "AsyncQueryEncounteredUserFacingError",
    "AsyncQueryMemoryExceededLimit",
    "AsyncQueryRuntimeError",
    "AsyncQueryTimeExceededLimit",
    "CancelExecutionNotSupported",
    "CancelExecutionPermissionDenied",
    "ConsistentSnapshotError",
    "ExecuteAsyncQueryPermissionDenied",
    "ExecuteQueryPermissionDenied",
    "ExecutionNotFound",
    "FunctionHasNoPublishedVersion",
    "FunctionNotFound",
    "FunctionNotSupportedWithTransaction",
    "GetByRidPermissionDenied",
    "GetResultExecutionPermissionDenied",
    "InvalidQueryOutputValue",
    "InvalidQueryParameterValue",
    "MissingParameter",
    "QueryEncounteredUserFacingError",
    "QueryMemoryExceededLimit",
    "QueryNotFound",
    "QueryRuntimeError",
    "QueryTimeExceededLimit",
    "QueryVersionNotFound",
    "StreamingExecuteEventsQueryPermissionDenied",
    "StreamingExecuteQueryPermissionDenied",
    "UnknownParameter",
    "ValueTypeNotFound",
    "VersionIdNotFound",
];
