//! AIP Agents service error names returned through [`crate::error::ApiError`].

pub const ERROR_NAMES: &[&str] = &[
    "ActionTypeNotFound",
    "AgentIterationsExceededLimit",
    "AgentNotFound",
    "AgentVersionNotFound",
    "BlockingContinueSessionPermissionDenied",
    "CancelSessionFailedMessageNotInProgress",
    "CancelSessionPermissionDenied",
    "ContentNotFound",
    "ContextSizeExceededLimit",
    "CreateSessionPermissionDenied",
    "DeleteSessionPermissionDenied",
    "FunctionLocatorNotFound",
    "GetAllSessionsAgentsPermissionDenied",
    "GetRagContextForSessionPermissionDenied",
    "InvalidAgentVersion",
    "InvalidParameter",
    "InvalidParameterType",
    "ListSessionsForAgentsPermissionDenied",
    "NoPublishedAgentVersion",
    "ObjectTypeIdsNotFound",
    "ObjectTypeRidsNotFound",
    "OntologyEntitiesNotFound",
    "RateLimitExceeded",
    "RetryAttemptsExceeded",
    "RetryDeadlineExceeded",
    "SessionExecutionFailed",
    "SessionNotFound",
    "SessionTraceIdAlreadyExists",
    "SessionTraceNotFound",
    "StreamingContinueSessionPermissionDenied",
    "UnsupportedLanguageModelRid",
    "UpdateSessionTitlePermissionDenied",
];
